version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: starwars-local-db
    restart: always
    environment:
      POSTGRES_DB: starwars_local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"